[package]
name = "example_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
serde = "1.0"
k256 = { version = "0.13", features = ["serde"] }
rand_core = "0.6.4"
